
package serviciosBusNow.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Tue May 12 09:15:33 CEST 2015
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "obtenerBusesDisponiblesResponse", namespace = "http://serviciosBusNow/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerBusesDisponiblesResponse", namespace = "http://serviciosBusNow/")

public class ObtenerBusesDisponiblesResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

