
package serviciosBusNow.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Tue May 12 09:15:32 CEST 2015
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "obtenerBusesNoAparcados", namespace = "http://serviciosBusNow/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obtenerBusesNoAparcados", namespace = "http://serviciosBusNow/")

public class ObtenerBusesNoAparcados {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

